#-------------------------------
# General Site Settings
baseurl: "" # The subpath of your site, e.g. /blog
url: "" # The base hostname & protocol for your site, e.g. http://example.com

title: metafarm74
logo:  /assets/images/MetaFarm74_Logo.png # You can add own logo
description: # Add your awesome description
copyright: Copyright 2022 Designed by [Alex Zander](https://www.labcr74tivefarm.com/) & Developed by [Shaan Patel](https://github.com/Epistetechnician)
# Preloader
preloader: true # To disable preloader change value to false

menu:
  - name: Home
    url: /
  - name: About
    url: /about/
    - submenu:
      - name: Mission
        url: /mission/
    - submenu:
      - name: Roadmap
        url: /roadmap/
    - submenu:
      - name: Team
        url: /team/        
  - name: Contact
    url: /contact/
# *** NOTE ***
# You can add submenus. For example:

#  menu:
#  - name: Home
#    url: /
#    submenu:
#     - name: Peru
#       url: /peru/
# ----------------------------------

layout_home_page: true # Homepage layout ( two layout is available, you can set the another layout by change the value of layout_home_page "true" to "false")

featured-post-slider: true # You can enable or disable the featured-post-slider using true or false values.

#-------------------------------
# Hero Section
hero:
  hero-subtitle: This is a cultural development initiative that aims to empower artists and marginalized communities by leveraging the applications of the decentralized web. The initiative is comprised of backing local community development projects through the release of recursive NFT collections.
  hero-banner: /assets/images/banner-img.png # Add your banner image '/assets/images/'

#-------------------------------
# Author Settings
author:
  name: Shaan Patel

#-------------------------------
# Contact Info
contact:
  email: support@metafarm74.xyz
  address:
    city: Los Angeles X New York City
    street: Metaversal Avenue

# Contact Form
contact-form: support@metafarm74.xyz

# Social links
social:
- {icon: "ti-twitter-alt", link: "#"}
- {icon: "ti-discord", link: "#"}
- {icon: "ti-github", link: "https://github.com/MetaFarm74"}
- {icon: "ti-instagram", link: "#"}

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
userID: 4044026246
accessToken: 4044026246.1677ed0.8896752506ed4402a0519d23b8f50a17

#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.

#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-archives

paginate: 10
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# categories
jekyll-archives:
  enabled: all
  layout: category
  permalinks:
    category: '/category/:name/'

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
